import { KulThemeElement } from "../kul-theme-declarations";
import { KUL_THEME_FONTS } from "./contants";

export const CINDER: KulThemeElement = {
  cssVariables: {
    "--kul-primary-color": "#afafaf",
    "--kul-secondary-color": "#333333",
    "--kul-background-color": "#101010",
    "--kul-header-background-color": "#1b1b1b",
    "--kul-header-color": "#e0e0e0",
    "--kul-drawer-background-color": "#1b1b1b",
    "--kul-drawer-color": "#e0e0e0",
    "--kul-header-height": "64px",
    "--kul-drawer-width": "300px",
    "--kul-font-family": "Inter, sans-serif",
    "--kul-font-family-monospace": "Fira Code, monospace",
    "--kul-font-size": "16px",
    "--kul-text-color": "#e0e0e0",
    "--kul-text-on-primary-color": "#1e1e1e",
    "--kul-text-on-secondary-color": "#e0e0e0",
    "--kul-disabled-background-color": "#333333",
    "--kul-disabled-color": "#666666",
    "--kul-title-background-color": "#2b2b2b",
    "--kul-title-color": "#e0e0e0",
    "--kul-icon-color": "#a1a1a1",
    "--kul-border-color": "#444444",
    "--kul-box-shadow": "0 8px 32px rgba(0, 0, 0, 0.4)",
    "--kul-info-color": "#56ccf2",
    "--kul-success-color": "#6fcf97",
    "--kul-warning-color": "#f2c94c",
    "--kul-danger-color": "#eb5757",
    "--kul-spinner-color": "#56ccf2",
    "--kul-chart-color-1": "#735DED",
    "--kul-chart-color-2": "#00B2CB",
    "--kul-chart-color-3": "#F2994A",
    "--kul-chart-color-4": "#27ae60",
    "--kul-card-zindex": 900,
    "--kul-drawer-zindex": 900,
    "--kul-header-zindex": 900,
  },
  icons: {
    "--kul-ascending-icon": "arrow_drop_up",
    "--kul-descending-icon": "arrow_drop_down",
    "--kul-expanded-icon": "arrow_drop_down",
    "--kul-collapsed-icon": "menu-right",
    "--kul-dropdown-icon": "arrow_drop_down",
    "--kul-clear-icon": "cancel",
    "--kul-filter-remove-icon": "filter-remove",
    "--kul-key-icon": "key-variant",
    "--kul-search-icon": "search",
    "--kul-warning-icon": "warning",
  },
  font: [KUL_THEME_FONTS.inter, KUL_THEME_FONTS.firaCode],
  isDark: true,
};
