import { KulThemeElement } from "../kul-theme-declarations";
import { KUL_THEME_FONTS } from "./contants";

export const COBALT: KulThemeElement = {
  cssVariables: {
    "--kul-primary-color": "#248aff",
    "--kul-secondary-color": "#65cbe9",
    "--kul-background-color": "#222222",
    "--kul-header-background-color": "#131313",
    "--kul-header-color": "#65cbe9",
    "--kul-drawer-background-color": "#2e2e2e",
    "--kul-drawer-color": "#65cbe9",
    "--kul-header-height": "64px",
    "--kul-drawer-width": "300px",
    "--kul-font-family": "Blinker, sans-serif;",
    "--kul-font-family-monospace": "Andalé Mono, monospace",
    "--kul-font-size": "14px",
    "--kul-text-color": "#65cbe9",
    "--kul-text-on-primary-color": "#f1f7ff",
    "--kul-text-on-secondary-color": "#000000",
    "--kul-disabled-background-color": "#3c3c3c",
    "--kul-disabled-color": "#7e7e7e",
    "--kul-title-background-color": "#2e2e2e",
    "--kul-title-color": "#f5f5f5",
    "--kul-icon-color": "#65cbe9",
    "--kul-border-color": "#535353",
    "--kul-box-shadow": "0px 0px 7.5px 0px rgba(128, 128, 128, 0.5)",
    "--kul-info-color": "#2592df",
    "--kul-success-color": "#4d9f02",
    "--kul-warning-color": "#ffc107",
    "--kul-danger-color": "#d91e18",
    "--kul-spinner-color": "#a4d9f7",
    "--kul-chart-color-1": "#308aff",
    "--kul-chart-color-2": "#5eb6d1",
    "--kul-chart-color-3": "#b1eafb",
    "--kul-chart-color-4": "#ffffff",
    "--kul-card-zindex": 900,
    "--kul-drawer-zindex": 900,
    "--kul-header-zindex": 900,
  },
  icons: {
    "--kul-ascending-icon": "arrow_drop_up",
    "--kul-descending-icon": "arrow_drop_down",
    "--kul-expanded-icon": "arrow_drop_down",
    "--kul-collapsed-icon": "menu-right",
    "--kul-dropdown-icon": "arrow_drop_down",
    "--kul-clear-icon": "cancel",
    "--kul-filter-remove-icon": "filter-remove",
    "--kul-key-icon": "key-variant",
    "--kul-search-icon": "search",
    "--kul-warning-icon": "warning",
  },
  font: [KUL_THEME_FONTS.blinker],
  isDark: true,
};
