import { KulThemeElement } from "../kul-theme-declarations";

export const GRAPHITE: KulThemeElement = {
  cssVariables: {
    "--kul-primary-color": "#888888",
    "--kul-secondary-color": "#d91e18",
    "--kul-background-color": "#ffffff",
    "--kul-header-background-color": "#535353",
    "--kul-header-color": "#ffffff",
    "--kul-drawer-background-color": "#ffffff",
    "--kul-drawer-color": "#545454",
    "--kul-header-height": "64px",
    "--kul-drawer-width": "300px",
    "--kul-font-family": "Roboto, sans-serif",
    "--kul-font-family-monospace": "Roboto Mono, consolas, monospace",
    "--kul-font-size": "13px",
    "--kul-text-color": "#545454",
    "--kul-text-on-primary-color": "#ffffff",
    "--kul-text-on-secondary-color": "#ffffff",
    "--kul-disabled-color": "#5c5c5c",
    "--kul-disabled-background-color": "#eaeaea",
    "--kul-title-background-color": "#f0f0f0",
    "--kul-title-color": "#545454",
    "--kul-icon-color": "#808080",
    "--kul-border-color": "#e0e0e0",
    "--kul-box-shadow": "0px 0px 7.5px 0px rgba(128, 128, 128, 0.5)",
    "--kul-info-color": "#2592df",
    "--kul-success-color": "#4d9f02",
    "--kul-warning-color": "#ffc107",
    "--kul-danger-color": "#d91e18",
    "--kul-spinner-color": "#eaa710",
    "--kul-chart-color-1": "red",
    "--kul-chart-color-2": "blue",
    "--kul-chart-color-3": "orange",
    "--kul-chart-color-4": "green",
    "--kul-chart-color-5": "yellow",
    "--kul-chart-color-6": "cyan",
    "--kul-chart-color-7": "brown",
    "--kul-chart-color-8": "magenta",
    "--kul-chart-color-9": "grey",
    "--kul-chart-color-10": "indigo",
    "--kul-card-zindex": 900,
    "--kul-drawer-zindex": 900,
    "--kul-header-zindex": 900,
  },
  customStyles: {
    "kul-BUTTON": "#kul-component button {\ntext-transform: unset;\n}\n\n",
  },
  icons: {
    "--kul-ascending-icon": "arrow_drop_up",
    "--kul-descending-icon": "arrow_drop_down",
    "--kul-expanded-icon": "arrow_drop_down",
    "--kul-collapsed-icon": "menu-right",
    "--kul-dropdown-icon": "arrow_drop_down",
    "--kul-clear-icon": "cancel",
    "--kul-filter-remove-icon": "filter-remove",
    "--kul-key-icon": "key-variant",
    "--kul-search-icon": "search",
    "--kul-warning-icon": "warning",
  },
  isDark: false,
};
