import { KulThemeElement } from "../kul-theme-declarations";

export const SAPPHIRE: KulThemeElement = {
  cssVariables: {
    "--kul-primary-color": "#003b77",
    "--kul-secondary-color": "#ff1414",
    "--kul-background-color": "#ffffff",
    "--kul-header-background-color": "#003b77",
    "--kul-header-color": "#ffffff",
    "--kul-drawer-background-color": "#002244",
    "--kul-drawer-color": "#ffffff",
    "--kul-header-height": "64px",
    "--kul-drawer-width": "20em",
    "--kul-font-family": "Arial",
    "--kul-font-family-monospace": "Arial",
    "--kul-font-size": "13px",
    "--kul-text-color": "#333333",
    "--kul-text-on-primary-color": "#fafafa",
    "--kul-text-on-secondary-color": "#ffffff",
    "--kul-disabled-background-color": "#ddecf8",
    "--kul-disabled-color": "#333333",
    "--kul-title-background-color": "#003b77",
    "--kul-title-color": "#ffffff",
    "--kul-icon-color": "#808080",
    "--kul-border-color": "#93c4ec",
    "--kul-box-shadow":
      "rgba(0, 0, 0, 0.2) 0px 5px 5px -3px, rgba(0, 0, 0, 0.14) 0px 8px 10px 1px, rgba(0, 0, 0, 0.12) 0px 3px 14px 2px",
    "--kul-info-color": "#2592df",
    "--kul-success-color": "#4d9f02",
    "--kul-warning-color": "#ffc107",
    "--kul-danger-color": "#a94442",
    "--kul-spinner-color": "#003b77",
    "--kul-chart-color-1": "#0781fd",
    "--kul-chart-color-2": "#002244",
    "--kul-chart-color-3": "#c6cff8",
    "--kul-chart-color-4": "#66bdda",
    "--kul-chart-color-5": "yellow",
    "--kul-chart-color-6": "cyan",
    "--kul-chart-color-7": "brown",
    "--kul-chart-color-8": "magenta",
    "--kul-chart-color-9": "grey",
    "--kul-chart-color-10": "indigo",
    "--kul-card-zindex": 900,
    "--kul-drawer-zindex": 900,
    "--kul-header-zindex": 900,
  },
  icons: {
    "--kul-ascending-icon": "arrow_drop_up",
    "--kul-descending-icon": "arrow_drop_down",
    "--kul-expanded-icon": "arrow_drop_down",
    "--kul-collapsed-icon": "menu-right",
    "--kul-dropdown-icon": "arrow_drop_down",
    "--kul-clear-icon": "cancel",
    "--kul-filter-remove-icon": "filter-remove",
    "--kul-key-icon": "key-variant",
    "--kul-search-icon": "search",
    "--kul-warning-icon": "warning",
  },
  isDark: false,
};
