import { KulThemeElement } from "../kul-theme-declarations";
import { KUL_THEME_FONTS } from "./contants";

export const SILVER: KulThemeElement = {
  cssVariables: {
    "--kul-primary-color": "#c0c0c0",
    "--kul-secondary-color": "#c0c0c0",
    "--kul-background-color": "#000000",
    "--kul-header-background-color": "#ffffff",
    "--kul-header-color": "#000000",
    "--kul-drawer-background-color": "#ffffff",
    "--kul-drawer-color": "#000000",
    "--kul-header-height": "80px",
    "--kul-drawer-width": "320px",
    "--kul-font-family": "Oswald, sans-serif",
    "--kul-font-family-monospace": "Xanh Mono, monospace",
    "--kul-font-size": "16px",
    "--kul-text-color": "#fefefe",
    "--kul-text-on-primary-color": "#4a4a4a",
    "--kul-text-on-secondary-color": "#4a4a4a",
    "--kul-disabled-background-color": "#3c3c3c",
    "--kul-disabled-color": "#7e7e7e",
    "--kul-title-background-color": "#151515",
    "--kul-title-color": "#d9d9d9",
    "--kul-icon-color": "#c0c0c0",
    "--kul-border-color": "#c0c0c0",
    "--kul-box-shadow": "0px 0px 7.5px 0px rgba(128, 128, 128, 0.5)",
    "--kul-info-color": "#2592df",
    "--kul-success-color": "#4d9f02",
    "--kul-warning-color": "#ffc107",
    "--kul-danger-color": "#d91e18",
    "--kul-spinner-color": "#c0c0c0",
    "--kul-chart-color-1": "#ffffff",
    "--kul-chart-color-2": "#979797",
    "--kul-chart-color-3": "#bababa",
    "--kul-chart-color-4": "#000000",
    "--kul-chart-color-5": "#b35454",
    "--kul-chart-color-6": "#59af57",
    "--kul-chart-color-7": "#aeaa5d",
    "--kul-card-zindex": 900,
    "--kul-drawer-zindex": 900,
    "--kul-header-zindex": 900,
  },
  icons: {
    "--kul-ascending-icon": "arrow_drop_up",
    "--kul-descending-icon": "arrow_drop_down",
    "--kul-expanded-icon": "arrow_drop_down",
    "--kul-collapsed-icon": "menu-right",
    "--kul-dropdown-icon": "arrow_drop_down",
    "--kul-clear-icon": "cancel",
    "--kul-filter-remove-icon": "filter-remove",
    "--kul-key-icon": "key-variant",
    "--kul-search-icon": "search",
    "--kul-warning-icon": "warning",
  },
  font: [KUL_THEME_FONTS.oswald],
  isDark: true,
};
