import { KulThemeElement } from "../kul-theme-declarations";
import { KUL_THEME_FONTS } from "./contants";

export const SNOW: KulThemeElement = {
  cssVariables: {
    "--kul-primary-color": "#525252",
    "--kul-secondary-color": "#e0e0e0",
    "--kul-background-color": "#f7f9fc",
    "--kul-header-background-color": "#ffffff",
    "--kul-header-color": "#333333",
    "--kul-drawer-background-color": "#ffffff",
    "--kul-drawer-color": "#333333",
    "--kul-header-height": "64px",
    "--kul-drawer-width": "300px",
    "--kul-font-family": "Inter, sans-serif",
    "--kul-font-family-monospace": "Fira Code, monospace",
    "--kul-font-size": "16px",
    "--kul-text-color": "#333333",
    "--kul-text-on-primary-color": "#ffffff",
    "--kul-text-on-secondary-color": "#333333",
    "--kul-disabled-background-color": "#eaeaea",
    "--kul-disabled-color": "#9c9c9c",
    "--kul-title-background-color": "#ffffff",
    "--kul-title-color": "#333333",
    "--kul-icon-color": "#5a5a5a",
    "--kul-border-color": "#d3d3d3",
    "--kul-box-shadow": "0 8px 32px rgba(31, 38, 135, 0.2)",
    "--kul-info-color": "#56ccf2",
    "--kul-success-color": "#6fcf97",
    "--kul-warning-color": "#f2c94c",
    "--kul-danger-color": "#eb5757",
    "--kul-spinner-color": "#8e8e8e",
    "--kul-chart-color-1": "#56ccf2",
    "--kul-chart-color-2": "#bb6bd9",
    "--kul-chart-color-3": "#f2994a",
    "--kul-chart-color-4": "#27ae60",
    "--kul-card-zindex": 900,
    "--kul-drawer-zindex": 900,
    "--kul-header-zindex": 900,
  },
  icons: {
    "--kul-ascending-icon": "arrow_drop_up",
    "--kul-descending-icon": "arrow_drop_down",
    "--kul-expanded-icon": "arrow_drop_down",
    "--kul-collapsed-icon": "menu-right",
    "--kul-dropdown-icon": "arrow_drop_down",
    "--kul-clear-icon": "cancel",
    "--kul-filter-remove-icon": "filter-remove",
    "--kul-key-icon": "key-variant",
    "--kul-search-icon": "search",
    "--kul-warning-icon": "warning",
  },
  font: [KUL_THEME_FONTS.inter, KUL_THEME_FONTS.firaCode],
  isDark: false,
};
