import { KulThemeElement } from "../kul-theme-declarations";
import { KUL_THEME_FONTFACE } from "./contants";

export const KETCHUP: KulThemeElement = {
  cssVariables: {
    "--kul-primary-color": "#d64325",
    "--kul-secondary-color": "#a6192e",
    "--kul-background-color": "#ffffff",
    "--kul-header-background-color": "#2e2e2e",
    "--kul-header-color": "#ffffff",
    "--kul-drawer-background-color": "#ffffff",
    "--kul-drawer-color": "#595959",
    "--kul-header-height": "64px",
    "--kul-drawer-width": "300px",
    "--kul-font-family": "Ubuntu, sans-serif",
    "--kul-font-family-monospace": "Roboto Mono, consolas, monospace",
    "--kul-font-size": "14px",
    "--kul-text-color": "#595959",
    "--kul-text-on-primary-color": "#ffffff",
    "--kul-text-on-secondary-color": "#ffffff",
    "--kul-disabled-background-color": "#eaeaea",
    "--kul-disabled-color": "#5c5c5c",
    "--kul-title-background-color": "#f1f3f4",
    "--kul-title-color": "#2e2e2e",
    "--kul-icon-color": "#505050",
    "--kul-border-color": "#e0e0e0",
    "--kul-box-shadow":
      "rgba(0, 0, 0, 0.2) 0px 5px 5px -3px, rgba(0, 0, 0, 0.14) 0px 8px 10px 1px, rgba(0, 0, 0, 0.12) 0px 3px 14px 2px",
    "--kul-info-color": "#2592df",
    "--kul-success-color": "#4d9f02",
    "--kul-warning-color": "#ffc107",
    "--kul-danger-color": "#d91e18",
    "--kul-spinner-color": "#eaa710",
    "--kul-chart-color-1": "#ff5959",
    "--kul-chart-color-2": "#e0a0a0",
    "--kul-chart-color-3": "#8e1010",
    "--kul-chart-color-4": "#f5f5dc",
    "--kul-card-zindex": 900,
    "--kul-drawer-zindex": 900,
    "--kul-header-zindex": 900,
  },
  icons: {
    "--kul-ascending-icon": "sort-ascending",
    "--kul-descending-icon": "sort-descending",
    "--kul-expanded-icon": "chevron-down",
    "--kul-collapsed-icon": "chevron_right",
    "--kul-dropdown-icon": "chevron-down",
    "--kul-clear-icon": "clear",
    "--kul-filter-remove-icon": "filter-remove",
    "--kul-key-icon": "key",
    "--kul-search-icon": "search",
    "--kul-warning-icon": "warning",
  },
  font: [KUL_THEME_FONTFACE.ubuntu],
  isDark: false,
};
