import { KulThemeElement } from "../kul-theme-declarations";
import { KUL_THEME_FONTFACE } from "./contants";

export const RED: KulThemeElement = {
  cssVariables: {
    "--kul-primary-color": "#a6192e",
    "--kul-secondary-color": "#ffc107",
    "--kul-background-color": "#ffffff",
    "--kul-header-background-color": "#a6192e",
    "--kul-header-color": "#ffffff",
    "--kul-drawer-background-color": "#f5f5f5",
    "--kul-drawer-color": "#000000",
    "--kul-header-height": "64px",
    "--kul-drawer-width": "300px",
    "--kul-font-family": "Open Sans, arial, helvatica",
    "--kul-font-family-monospace": "Roboto Mono, consolas, monospace",
    "--kul-font-size": "13px",
    "--kul-text-color": "#000000",
    "--kul-text-on-primary-color": "#ffffff",
    "--kul-text-on-secondary-color": "#ffffff",
    "--kul-disabled-background-color": "#eaeaea",
    "--kul-disabled-color": "#333333",
    "--kul-title-background-color": "#f1f3f4",
    "--kul-title-color": "#2e2e2e",
    "--kul-icon-color": "#808080",
    "--kul-border-color": "#ededed",
    "--kul-box-shadow":
      "rgba(0, 0, 0, 0.2) 0px 5px 5px -3px, rgba(0, 0, 0, 0.14) 0px 8px 10px 1px, rgba(0, 0, 0, 0.12) 0px 3px 14px 2px",
    "--kul-info-color": "#2592df",
    "--kul-success-color": "#4d9f02",
    "--kul-warning-color": "#ffc107",
    "--kul-danger-color": "#A6192E",
    "--kul-spinner-color": "#1D1D1B",
    "--kul-chart-color-1": "#735DED",
    "--kul-chart-color-2": "#00B2CB",
    "--kul-chart-color-3": "#EDC900",
    "--kul-chart-color-4": "#a6192e",
    "--kul-chart-color-5": "yellow",
    "--kul-chart-color-6": "cyan",
    "--kul-chart-color-7": "brown",
    "--kul-chart-color-8": "magenta",
    "--kul-chart-color-9": "grey",
    "--kul-chart-color-10": "indigo",
    "--kul-card-zindex": 900,
    "--kul-drawer-zindex": 900,
    "--kul-header-zindex": 900,
  },
  icons: {
    "--kul-ascending-icon": "arrow_drop_up",
    "--kul-descending-icon": "arrow_drop_down",
    "--kul-expanded-icon": "arrow_drop_down",
    "--kul-collapsed-icon": "menu-right",
    "--kul-dropdown-icon": "arrow_drop_down",
    "--kul-clear-icon": "cancel",
    "--kul-filter-remove-icon": "filter-remove",
    "--kul-key-icon": "key-variant",
    "--kul-search-icon": "search",
    "--kul-warning-icon": "warning",
  },
  font: [KUL_THEME_FONTFACE.openSans],
  isDark: false,
};
