import { KulThemeElement } from "../kul-theme-declarations";
import { KUL_THEME_FONTFACE } from "./contants";

export const OCEAN: KulThemeElement = {
  cssVariables: {
    "--kul-primary-color": "#0074b7",
    "--kul-secondary-color": "#a2d5f2",
    "--kul-background-color": "#f0f8ff",
    "--kul-header-background-color": "#013a6b",
    "--kul-header-color": "#ffffff",
    "--kul-drawer-background-color": "#e1eff7",
    "--kul-font-family": "Public Sans, sans-serif",
    "--kul-text-color": "#1e2a33",
    "--kul-icon-color": "#5a7da0",
    "--kul-border-color": "#b8d3e4",
    "--kul-box-shadow": "0px 2px 8px rgba(0, 0, 0, 0.1)",
    "--kul-chart-color-1": "#8fcfe3",
    "--kul-chart-color-2": "#a2b7cf",
    "--kul-chart-color-3": "#d9f1ff",
    "--kul-chart-color-4": "#93b1c4",
    "--kul-drawer-color": "#1b1b1b",
    "--kul-header-height": "64px",
    "--kul-drawer-width": "300px",
    "--kul-font-family-monospace": "Roboto Mono, consolas, monospace",
    "--kul-font-size": "16px",
    "--kul-text-on-primary-color": "#ffffff",
    "--kul-text-on-secondary-color": "#ffffff",
    "--kul-disabled-background-color": "#eaeaea",
    "--kul-disabled-color": "#5c5c5c",
    "--kul-title-background-color": "#f1f3f4",
    "--kul-title-color": "#1b1b1b",
    "--kul-info-color": "#2592df",
    "--kul-success-color": "#4d9f02",
    "--kul-warning-color": "#ffc107",
    "--kul-danger-color": "#d91e18",
    "--kul-spinner-color": "#6edeff",
    "--kul-card-zindex": 900,
    "--kul-drawer-zindex": 900,
    "--kul-header-zindex": 900,
  },
  icons: {
    "--kul-ascending-icon": "arrow_drop_up",
    "--kul-descending-icon": "arrow_drop_down",
    "--kul-expanded-icon": "arrow_drop_down",
    "--kul-collapsed-icon": "menu-right",
    "--kul-dropdown-icon": "arrow_drop_down",
    "--kul-clear-icon": "cancel",
    "--kul-filter-remove-icon": "filter-remove",
    "--kul-key-icon": "key-variant",
    "--kul-search-icon": "search",
    "--kul-warning-icon": "warning",
  },
  font: [KUL_THEME_FONTFACE.publicSans],
  isDark: false,
};
