import { KulThemeElement } from "../kul-theme-declarations";
import { KUL_THEME_FONTFACE } from "./contants";

export const WILDLIFE: KulThemeElement = {
  cssVariables: {
    "--kul-primary-color": "#1a7340",
    "--kul-secondary-color": "#826a4a",
    "--kul-background-color": "#f9f9f5",
    "--kul-header-background-color": "#12522e",
    "--kul-header-color": "#ffffff",
    "--kul-drawer-background-color": "#e7f2e1",
    "--kul-drawer-color": "#000000",
    "--kul-font-family": "Crimson Text, serif",
    "--kul-font-family-monospace": "Roboto Mono, consolas, monospace",
    "--kul-text-color": "#1a1a1a",
    "--kul-box-shadow": "0px 4px 10px rgba(0, 0, 0, 0.15)",
    "--kul-icon-color": "#4e8c57",
    "--kul-border-color": "#c4c4c4",
    "--kul-chart-color-1": "#58a27f",
    "--kul-chart-color-2": "#a9c1a1",
    "--kul-chart-color-3": "#6e8d5e",
    "--kul-chart-color-4": "#f0f2e7",
    "--kul-header-height": "64px",
    "--kul-drawer-width": "300px",
    "--kul-font-size": "16px",
    "--kul-text-on-primary-color": "#ffffff",
    "--kul-text-on-secondary-color": "#ffffff",
    "--kul-disabled-background-color": "#eaeaea",
    "--kul-disabled-color": "#5c5c5c",
    "--kul-title-background-color": "#f1f3f4",
    "--kul-title-color": "#000000",
    "--kul-info-color": "#2592df",
    "--kul-success-color": "#4d9f02",
    "--kul-warning-color": "#ffc107",
    "--kul-danger-color": "#d91e18",
    "--kul-spinner-color": "#44b383",
    "--kul-card-zindex": 900,
    "--kul-drawer-zindex": 900,
    "--kul-header-zindex": 900,
  },
  icons: {
    "--kul-ascending-icon": "arrow_drop_up",
    "--kul-descending-icon": "arrow_drop_down",
    "--kul-expanded-icon": "arrow_drop_down",
    "--kul-collapsed-icon": "menu-right",
    "--kul-dropdown-icon": "arrow_drop_down",
    "--kul-clear-icon": "cancel",
    "--kul-filter-remove-icon": "filter-remove",
    "--kul-key-icon": "key-variant",
    "--kul-search-icon": "search",
    "--kul-warning-icon": "warning",
  },
  font: [KUL_THEME_FONTFACE.crimsonText],
  isDark: false,
};
