/* eslint-disable */
/* tslint:disable */
/* auto-generated react proxies */
import { createReactComponent } from './react-component-lib';

import type { JSX } from 'ketchup-lite';

import { defineCustomElements } from 'ketchup-lite/dist/loader';

defineCustomElements();
export const KulAccordion = /*@__PURE__*/createReactComponent<JSX.KulAccordion, HTMLKulAccordionElement>('kul-accordion');
export const KulArticle = /*@__PURE__*/createReactComponent<JSX.KulArticle, HTMLKulArticleElement>('kul-article');
export const KulBadge = /*@__PURE__*/createReactComponent<JSX.KulBadge, HTMLKulBadgeElement>('kul-badge');
export const KulButton = /*@__PURE__*/createReactComponent<JSX.KulButton, HTMLKulButtonElement>('kul-button');
export const KulCanvas = /*@__PURE__*/createReactComponent<JSX.KulCanvas, HTMLKulCanvasElement>('kul-canvas');
export const KulCard = /*@__PURE__*/createReactComponent<JSX.KulCard, HTMLKulCardElement>('kul-card');
export const KulCarousel = /*@__PURE__*/createReactComponent<JSX.KulCarousel, HTMLKulCarouselElement>('kul-carousel');
export const KulChart = /*@__PURE__*/createReactComponent<JSX.KulChart, HTMLKulChartElement>('kul-chart');
export const KulChat = /*@__PURE__*/createReactComponent<JSX.KulChat, HTMLKulChatElement>('kul-chat');
export const KulChip = /*@__PURE__*/createReactComponent<JSX.KulChip, HTMLKulChipElement>('kul-chip');
export const KulCode = /*@__PURE__*/createReactComponent<JSX.KulCode, HTMLKulCodeElement>('kul-code');
export const KulCompare = /*@__PURE__*/createReactComponent<JSX.KulCompare, HTMLKulCompareElement>('kul-compare');
export const KulDrawer = /*@__PURE__*/createReactComponent<JSX.KulDrawer, HTMLKulDrawerElement>('kul-drawer');
export const KulHeader = /*@__PURE__*/createReactComponent<JSX.KulHeader, HTMLKulHeaderElement>('kul-header');
export const KulImage = /*@__PURE__*/createReactComponent<JSX.KulImage, HTMLKulImageElement>('kul-image');
export const KulImageviewer = /*@__PURE__*/createReactComponent<JSX.KulImageviewer, HTMLKulImageviewerElement>('kul-imageviewer');
export const KulLazy = /*@__PURE__*/createReactComponent<JSX.KulLazy, HTMLKulLazyElement>('kul-lazy');
export const KulList = /*@__PURE__*/createReactComponent<JSX.KulList, HTMLKulListElement>('kul-list');
export const KulMasonry = /*@__PURE__*/createReactComponent<JSX.KulMasonry, HTMLKulMasonryElement>('kul-masonry');
export const KulMessenger = /*@__PURE__*/createReactComponent<JSX.KulMessenger, HTMLKulMessengerElement>('kul-messenger');
export const KulPhotoframe = /*@__PURE__*/createReactComponent<JSX.KulPhotoframe, HTMLKulPhotoframeElement>('kul-photoframe');
export const KulProgressbar = /*@__PURE__*/createReactComponent<JSX.KulProgressbar, HTMLKulProgressbarElement>('kul-progressbar');
export const KulShowcase = /*@__PURE__*/createReactComponent<JSX.KulShowcase, HTMLKulShowcaseElement>('kul-showcase');
export const KulShowcaseAccordion = /*@__PURE__*/createReactComponent<JSX.KulShowcaseAccordion, HTMLKulShowcaseAccordionElement>('kul-showcase-accordion');
export const KulShowcaseArticle = /*@__PURE__*/createReactComponent<JSX.KulShowcaseArticle, HTMLKulShowcaseArticleElement>('kul-showcase-article');
export const KulShowcaseBadge = /*@__PURE__*/createReactComponent<JSX.KulShowcaseBadge, HTMLKulShowcaseBadgeElement>('kul-showcase-badge');
export const KulShowcaseButton = /*@__PURE__*/createReactComponent<JSX.KulShowcaseButton, HTMLKulShowcaseButtonElement>('kul-showcase-button');
export const KulShowcaseCanvas = /*@__PURE__*/createReactComponent<JSX.KulShowcaseCanvas, HTMLKulShowcaseCanvasElement>('kul-showcase-canvas');
export const KulShowcaseCard = /*@__PURE__*/createReactComponent<JSX.KulShowcaseCard, HTMLKulShowcaseCardElement>('kul-showcase-card');
export const KulShowcaseCarousel = /*@__PURE__*/createReactComponent<JSX.KulShowcaseCarousel, HTMLKulShowcaseCarouselElement>('kul-showcase-carousel');
export const KulShowcaseChart = /*@__PURE__*/createReactComponent<JSX.KulShowcaseChart, HTMLKulShowcaseChartElement>('kul-showcase-chart');
export const KulShowcaseChat = /*@__PURE__*/createReactComponent<JSX.KulShowcaseChat, HTMLKulShowcaseChatElement>('kul-showcase-chat');
export const KulShowcaseChip = /*@__PURE__*/createReactComponent<JSX.KulShowcaseChip, HTMLKulShowcaseChipElement>('kul-showcase-chip');
export const KulShowcaseCode = /*@__PURE__*/createReactComponent<JSX.KulShowcaseCode, HTMLKulShowcaseCodeElement>('kul-showcase-code');
export const KulShowcaseCompare = /*@__PURE__*/createReactComponent<JSX.KulShowcaseCompare, HTMLKulShowcaseCompareElement>('kul-showcase-compare');
export const KulShowcaseDebug = /*@__PURE__*/createReactComponent<JSX.KulShowcaseDebug, HTMLKulShowcaseDebugElement>('kul-showcase-debug');
export const KulShowcaseDrawer = /*@__PURE__*/createReactComponent<JSX.KulShowcaseDrawer, HTMLKulShowcaseDrawerElement>('kul-showcase-drawer');
export const KulShowcaseHeader = /*@__PURE__*/createReactComponent<JSX.KulShowcaseHeader, HTMLKulShowcaseHeaderElement>('kul-showcase-header');
export const KulShowcaseImage = /*@__PURE__*/createReactComponent<JSX.KulShowcaseImage, HTMLKulShowcaseImageElement>('kul-showcase-image');
export const KulShowcaseImageviewer = /*@__PURE__*/createReactComponent<JSX.KulShowcaseImageviewer, HTMLKulShowcaseImageviewerElement>('kul-showcase-imageviewer');
export const KulShowcaseKuldata = /*@__PURE__*/createReactComponent<JSX.KulShowcaseKuldata, HTMLKulShowcaseKuldataElement>('kul-showcase-kuldata');
export const KulShowcaseKuldates = /*@__PURE__*/createReactComponent<JSX.KulShowcaseKuldates, HTMLKulShowcaseKuldatesElement>('kul-showcase-kuldates');
export const KulShowcaseKuldebug = /*@__PURE__*/createReactComponent<JSX.KulShowcaseKuldebug, HTMLKulShowcaseKuldebugElement>('kul-showcase-kuldebug');
export const KulShowcaseKuldynamicposition = /*@__PURE__*/createReactComponent<JSX.KulShowcaseKuldynamicposition, HTMLKulShowcaseKuldynamicpositionElement>('kul-showcase-kuldynamicposition');
export const KulShowcaseKullanguage = /*@__PURE__*/createReactComponent<JSX.KulShowcaseKullanguage, HTMLKulShowcaseKullanguageElement>('kul-showcase-kullanguage');
export const KulShowcaseKulllm = /*@__PURE__*/createReactComponent<JSX.KulShowcaseKulllm, HTMLKulShowcaseKulllmElement>('kul-showcase-kulllm');
export const KulShowcaseKulmanager = /*@__PURE__*/createReactComponent<JSX.KulShowcaseKulmanager, HTMLKulShowcaseKulmanagerElement>('kul-showcase-kulmanager');
export const KulShowcaseKulscrollonhover = /*@__PURE__*/createReactComponent<JSX.KulShowcaseKulscrollonhover, HTMLKulShowcaseKulscrollonhoverElement>('kul-showcase-kulscrollonhover');
export const KulShowcaseKultheme = /*@__PURE__*/createReactComponent<JSX.KulShowcaseKultheme, HTMLKulShowcaseKulthemeElement>('kul-showcase-kultheme');
export const KulShowcaseLazy = /*@__PURE__*/createReactComponent<JSX.KulShowcaseLazy, HTMLKulShowcaseLazyElement>('kul-showcase-lazy');
export const KulShowcaseList = /*@__PURE__*/createReactComponent<JSX.KulShowcaseList, HTMLKulShowcaseListElement>('kul-showcase-list');
export const KulShowcaseMasonry = /*@__PURE__*/createReactComponent<JSX.KulShowcaseMasonry, HTMLKulShowcaseMasonryElement>('kul-showcase-masonry');
export const KulShowcaseMessenger = /*@__PURE__*/createReactComponent<JSX.KulShowcaseMessenger, HTMLKulShowcaseMessengerElement>('kul-showcase-messenger');
export const KulShowcasePhotoframe = /*@__PURE__*/createReactComponent<JSX.KulShowcasePhotoframe, HTMLKulShowcasePhotoframeElement>('kul-showcase-photoframe');
export const KulShowcaseProgressbar = /*@__PURE__*/createReactComponent<JSX.KulShowcaseProgressbar, HTMLKulShowcaseProgressbarElement>('kul-showcase-progressbar');
export const KulShowcaseSlider = /*@__PURE__*/createReactComponent<JSX.KulShowcaseSlider, HTMLKulShowcaseSliderElement>('kul-showcase-slider');
export const KulShowcaseSpinner = /*@__PURE__*/createReactComponent<JSX.KulShowcaseSpinner, HTMLKulShowcaseSpinnerElement>('kul-showcase-spinner');
export const KulShowcaseSplash = /*@__PURE__*/createReactComponent<JSX.KulShowcaseSplash, HTMLKulShowcaseSplashElement>('kul-showcase-splash');
export const KulShowcaseTabbar = /*@__PURE__*/createReactComponent<JSX.KulShowcaseTabbar, HTMLKulShowcaseTabbarElement>('kul-showcase-tabbar');
export const KulShowcaseTextfield = /*@__PURE__*/createReactComponent<JSX.KulShowcaseTextfield, HTMLKulShowcaseTextfieldElement>('kul-showcase-textfield');
export const KulShowcaseToast = /*@__PURE__*/createReactComponent<JSX.KulShowcaseToast, HTMLKulShowcaseToastElement>('kul-showcase-toast');
export const KulShowcaseToggle = /*@__PURE__*/createReactComponent<JSX.KulShowcaseToggle, HTMLKulShowcaseToggleElement>('kul-showcase-toggle');
export const KulShowcaseTree = /*@__PURE__*/createReactComponent<JSX.KulShowcaseTree, HTMLKulShowcaseTreeElement>('kul-showcase-tree');
export const KulShowcaseTypewriter = /*@__PURE__*/createReactComponent<JSX.KulShowcaseTypewriter, HTMLKulShowcaseTypewriterElement>('kul-showcase-typewriter');
export const KulShowcaseUpload = /*@__PURE__*/createReactComponent<JSX.KulShowcaseUpload, HTMLKulShowcaseUploadElement>('kul-showcase-upload');
export const KulSlider = /*@__PURE__*/createReactComponent<JSX.KulSlider, HTMLKulSliderElement>('kul-slider');
export const KulSpinner = /*@__PURE__*/createReactComponent<JSX.KulSpinner, HTMLKulSpinnerElement>('kul-spinner');
export const KulSplash = /*@__PURE__*/createReactComponent<JSX.KulSplash, HTMLKulSplashElement>('kul-splash');
export const KulTabbar = /*@__PURE__*/createReactComponent<JSX.KulTabbar, HTMLKulTabbarElement>('kul-tabbar');
export const KulTextfield = /*@__PURE__*/createReactComponent<JSX.KulTextfield, HTMLKulTextfieldElement>('kul-textfield');
export const KulToast = /*@__PURE__*/createReactComponent<JSX.KulToast, HTMLKulToastElement>('kul-toast');
export const KulToggle = /*@__PURE__*/createReactComponent<JSX.KulToggle, HTMLKulToggleElement>('kul-toggle');
export const KulTree = /*@__PURE__*/createReactComponent<JSX.KulTree, HTMLKulTreeElement>('kul-tree');
export const KulTypewriter = /*@__PURE__*/createReactComponent<JSX.KulTypewriter, HTMLKulTypewriterElement>('kul-typewriter');
export const KulUpload = /*@__PURE__*/createReactComponent<JSX.KulUpload, HTMLKulUploadElement>('kul-upload');
