'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { type KulArticleCustomEvent, type KulArticleEventPayload } from "ketchup-lite";
import { KulArticle as KulArticleElement, defineCustomElement as defineKulArticle } from "ketchup-lite/dist/components/kul-article.js";
import React from 'react';

type KulArticleEvents = { onKulArticleEvent: EventName<KulArticleCustomEvent<KulArticleEventPayload>> };

const KulArticle: StencilReactComponent<KulArticleElement, KulArticleEvents> = /*@__PURE__*/ createComponent<KulArticleElement, KulArticleEvents>({
    tagName: 'kul-article',
    elementClass: KulArticleElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onKulArticleEvent: 'kul-article-event' } as KulArticleEvents,
    defineCustomElement: defineKulArticle
});

export default KulArticle;
