'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { type KulAccordionCustomEvent, type KulAccordionEventPayload } from "ketchup-lite";
import { KulAccordion as KulAccordionElement, defineCustomElement as defineKulAccordion } from "ketchup-lite/dist/components/kul-accordion.js";
import React from 'react';

type KulAccordionEvents = { onKulAccordionEvent: EventName<KulAccordionCustomEvent<KulAccordionEventPayload>> };

const KulAccordion: StencilReactComponent<KulAccordionElement, KulAccordionEvents> = /*@__PURE__*/ createComponent<KulAccordionElement, KulAccordionEvents>({
    tagName: 'kul-accordion',
    elementClass: KulAccordionElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onKulAccordionEvent: 'kul-accordion-event' } as KulAccordionEvents,
    defineCustomElement: defineKulAccordion
});

export default KulAccordion;
