'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { type KulBadgeCustomEvent, type KulBadgeEventPayload } from "ketchup-lite";
import { KulBadge as KulBadgeElement, defineCustomElement as defineKulBadge } from "ketchup-lite/dist/components/kul-badge.js";
import React from 'react';

type KulBadgeEvents = { onKulBadgeEvent: EventName<KulBadgeCustomEvent<KulBadgeEventPayload>> };

const KulBadge: StencilReactComponent<KulBadgeElement, KulBadgeEvents> = /*@__PURE__*/ createComponent<KulBadgeElement, KulBadgeEvents>({
    tagName: 'kul-badge',
    elementClass: KulBadgeElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onKulBadgeEvent: 'kul-badge-event' } as KulBadgeEvents,
    defineCustomElement: defineKulBadge
});

export default KulBadge;
