'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { type KulChartCustomEvent, type KulChartEventPayload } from "ketchup-lite";
import { KulChart as KulChartElement, defineCustomElement as defineKulChart } from "ketchup-lite/dist/components/kul-chart.js";
import React from 'react';

type KulChartEvents = { onKulChartEvent: EventName<KulChartCustomEvent<KulChartEventPayload>> };

const KulChart: StencilReactComponent<KulChartElement, KulChartEvents> = /*@__PURE__*/ createComponent<KulChartElement, KulChartEvents>({
    tagName: 'kul-chart',
    elementClass: KulChartElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onKulChartEvent: 'kul-chart-event' } as KulChartEvents,
    defineCustomElement: defineKulChart
});

export default KulChart;
