'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { type KulCompareCustomEvent, type KulCompareEventPayload } from "ketchup-lite";
import { KulCompare as KulCompareElement, defineCustomElement as defineKulCompare } from "ketchup-lite/dist/components/kul-compare.js";
import React from 'react';

type KulCompareEvents = { onKulCompareEvent: EventName<KulCompareCustomEvent<KulCompareEventPayload>> };

const KulCompare: StencilReactComponent<KulCompareElement, KulCompareEvents> = /*@__PURE__*/ createComponent<KulCompareElement, KulCompareEvents>({
    tagName: 'kul-compare',
    elementClass: KulCompareElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onKulCompareEvent: 'kul-compare-event' } as KulCompareEvents,
    defineCustomElement: defineKulCompare
});

export default KulCompare;
