'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { type KulChipCustomEvent, type KulChipEventPayload } from "ketchup-lite";
import { KulChip as KulChipElement, defineCustomElement as defineKulChip } from "ketchup-lite/dist/components/kul-chip.js";
import React from 'react';

type KulChipEvents = { onKulChipEvent: EventName<KulChipCustomEvent<KulChipEventPayload>> };

const KulChip: StencilReactComponent<KulChipElement, KulChipEvents> = /*@__PURE__*/ createComponent<KulChipElement, KulChipEvents>({
    tagName: 'kul-chip',
    elementClass: KulChipElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onKulChipEvent: 'kul-chip-event' } as KulChipEvents,
    defineCustomElement: defineKulChip
});

export default KulChip;
