'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { type KulCarouselCustomEvent, type KulCarouselEventPayload } from "ketchup-lite";
import { KulCarousel as KulCarouselElement, defineCustomElement as defineKulCarousel } from "ketchup-lite/dist/components/kul-carousel.js";
import React from 'react';

type KulCarouselEvents = { onKulCarouselEvent: EventName<KulCarouselCustomEvent<KulCarouselEventPayload>> };

const KulCarousel: StencilReactComponent<KulCarouselElement, KulCarouselEvents> = /*@__PURE__*/ createComponent<KulCarouselElement, KulCarouselEvents>({
    tagName: 'kul-carousel',
    elementClass: KulCarouselElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onKulCarouselEvent: 'kul-carousel-event' } as KulCarouselEvents,
    defineCustomElement: defineKulCarousel
});

export default KulCarousel;
