'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { type KulCardCustomEvent, type KulCardEventPayload } from "ketchup-lite";
import { KulCard as KulCardElement, defineCustomElement as defineKulCard } from "ketchup-lite/dist/components/kul-card.js";
import React from 'react';

type KulCardEvents = { onKulCardEvent: EventName<KulCardCustomEvent<KulCardEventPayload>> };

const KulCard: StencilReactComponent<KulCardElement, KulCardEvents> = /*@__PURE__*/ createComponent<KulCardElement, KulCardEvents>({
    tagName: 'kul-card',
    elementClass: KulCardElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onKulCardEvent: 'kul-card-event' } as KulCardEvents,
    defineCustomElement: defineKulCard
});

export default KulCard;
