'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { type KulChatCustomEvent, type KulChatEventPayload } from "ketchup-lite";
import { KulChat as KulChatElement, defineCustomElement as defineKulChat } from "ketchup-lite/dist/components/kul-chat.js";
import React from 'react';

type KulChatEvents = { onKulChatEvent: EventName<KulChatCustomEvent<KulChatEventPayload>> };

const KulChat: StencilReactComponent<KulChatElement, KulChatEvents> = /*@__PURE__*/ createComponent<KulChatElement, KulChatEvents>({
    tagName: 'kul-chat',
    elementClass: KulChatElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onKulChatEvent: 'kul-chat-event' } as KulChatEvents,
    defineCustomElement: defineKulChat
});

export default KulChat;
