'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { type KulCodeCustomEvent, type KulCodeEventPayload } from "ketchup-lite";
import { KulCode as KulCodeElement, defineCustomElement as defineKulCode } from "ketchup-lite/dist/components/kul-code.js";
import React from 'react';

type KulCodeEvents = { onKulCodeEvent: EventName<KulCodeCustomEvent<KulCodeEventPayload>> };

const KulCode: StencilReactComponent<KulCodeElement, KulCodeEvents> = /*@__PURE__*/ createComponent<KulCodeElement, KulCodeEvents>({
    tagName: 'kul-code',
    elementClass: KulCodeElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onKulCodeEvent: 'kul-code-event' } as KulCodeEvents,
    defineCustomElement: defineKulCode
});

export default KulCode;
