'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { type KulDrawerCustomEvent, type KulDrawerEventPayload } from "ketchup-lite";
import { KulDrawer as KulDrawerElement, defineCustomElement as defineKulDrawer } from "ketchup-lite/dist/components/kul-drawer.js";
import React from 'react';

type KulDrawerEvents = { onKulDrawerEvent: EventName<KulDrawerCustomEvent<KulDrawerEventPayload>> };

const KulDrawer: StencilReactComponent<KulDrawerElement, KulDrawerEvents> = /*@__PURE__*/ createComponent<KulDrawerElement, KulDrawerEvents>({
    tagName: 'kul-drawer',
    elementClass: KulDrawerElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onKulDrawerEvent: 'kul-drawer-event' } as KulDrawerEvents,
    defineCustomElement: defineKulDrawer
});

export default KulDrawer;
