'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { type KulHeaderCustomEvent, type KulHeaderEventPayload } from "ketchup-lite";
import { KulHeader as KulHeaderElement, defineCustomElement as defineKulHeader } from "ketchup-lite/dist/components/kul-header.js";
import React from 'react';

type KulHeaderEvents = { onKulHeaderEvent: EventName<KulHeaderCustomEvent<KulHeaderEventPayload>> };

const KulHeader: StencilReactComponent<KulHeaderElement, KulHeaderEvents> = /*@__PURE__*/ createComponent<KulHeaderElement, KulHeaderEvents>({
    tagName: 'kul-header',
    elementClass: KulHeaderElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onKulHeaderEvent: 'kul-header-event' } as KulHeaderEvents,
    defineCustomElement: defineKulHeader
});

export default KulHeader;
