'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { type KulImageviewerCustomEvent, type KulImageviewerEventPayload } from "ketchup-lite";
import { KulImageviewer as KulImageviewerElement, defineCustomElement as defineKulImageviewer } from "ketchup-lite/dist/components/kul-imageviewer.js";
import React from 'react';

type KulImageviewerEvents = { onKulImageviewerEvent: EventName<KulImageviewerCustomEvent<KulImageviewerEventPayload>> };

const KulImageviewer: StencilReactComponent<KulImageviewerElement, KulImageviewerEvents> = /*@__PURE__*/ createComponent<KulImageviewerElement, KulImageviewerEvents>({
    tagName: 'kul-imageviewer',
    elementClass: KulImageviewerElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onKulImageviewerEvent: 'kul-imageviewer-event' } as KulImageviewerEvents,
    defineCustomElement: defineKulImageviewer
});

export default KulImageviewer;
