'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { type KulImageCustomEvent, type KulImageEventPayload } from "ketchup-lite";
import { KulImage as KulImageElement, defineCustomElement as defineKulImage } from "ketchup-lite/dist/components/kul-image.js";
import React from 'react';

type KulImageEvents = { onKulImageEvent: EventName<KulImageCustomEvent<KulImageEventPayload>> };

const KulImage: StencilReactComponent<KulImageElement, KulImageEvents> = /*@__PURE__*/ createComponent<KulImageElement, KulImageEvents>({
    tagName: 'kul-image',
    elementClass: KulImageElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onKulImageEvent: 'kul-image-event' } as KulImageEvents,
    defineCustomElement: defineKulImage
});

export default KulImage;
