'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { type KulLazyCustomEvent, type KulLazyEventPayload } from "ketchup-lite";
import { KulLazy as KulLazyElement, defineCustomElement as defineKulLazy } from "ketchup-lite/dist/components/kul-lazy.js";
import React from 'react';

type KulLazyEvents = { onKulLazyEvent: EventName<KulLazyCustomEvent<KulLazyEventPayload>> };

const KulLazy: StencilReactComponent<KulLazyElement, KulLazyEvents> = /*@__PURE__*/ createComponent<KulLazyElement, KulLazyEvents>({
    tagName: 'kul-lazy',
    elementClass: KulLazyElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onKulLazyEvent: 'kul-lazy-event' } as KulLazyEvents,
    defineCustomElement: defineKulLazy
});

export default KulLazy;
