'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { type KulListCustomEvent, type KulListEventPayload } from "ketchup-lite";
import { KulList as KulListElement, defineCustomElement as defineKulList } from "ketchup-lite/dist/components/kul-list.js";
import React from 'react';

type KulListEvents = { onKulListEvent: EventName<KulListCustomEvent<KulListEventPayload>> };

const KulList: StencilReactComponent<KulListElement, KulListEvents> = /*@__PURE__*/ createComponent<KulListElement, KulListEvents>({
    tagName: 'kul-list',
    elementClass: KulListElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onKulListEvent: 'kul-list-event' } as KulListEvents,
    defineCustomElement: defineKulList
});

export default KulList;
