'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { type KulMasonryCustomEvent, type KulMasonryEventPayload } from "ketchup-lite";
import { KulMasonry as KulMasonryElement, defineCustomElement as defineKulMasonry } from "ketchup-lite/dist/components/kul-masonry.js";
import React from 'react';

type KulMasonryEvents = { onKulMasonryEvent: EventName<KulMasonryCustomEvent<KulMasonryEventPayload>> };

const KulMasonry: StencilReactComponent<KulMasonryElement, KulMasonryEvents> = /*@__PURE__*/ createComponent<KulMasonryElement, KulMasonryEvents>({
    tagName: 'kul-masonry',
    elementClass: KulMasonryElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onKulMasonryEvent: 'kul-masonry-event' } as KulMasonryEvents,
    defineCustomElement: defineKulMasonry
});

export default KulMasonry;
