'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { type KulProgressbarCustomEvent, type KulProgressbarEventPayload } from "ketchup-lite";
import { KulProgressbar as KulProgressbarElement, defineCustomElement as defineKulProgressbar } from "ketchup-lite/dist/components/kul-progressbar.js";
import React from 'react';

type KulProgressbarEvents = { onKulProgressbarEvent: EventName<KulProgressbarCustomEvent<KulProgressbarEventPayload>> };

const KulProgressbar: StencilReactComponent<KulProgressbarElement, KulProgressbarEvents> = /*@__PURE__*/ createComponent<KulProgressbarElement, KulProgressbarEvents>({
    tagName: 'kul-progressbar',
    elementClass: KulProgressbarElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onKulProgressbarEvent: 'kul-progressbar-event' } as KulProgressbarEvents,
    defineCustomElement: defineKulProgressbar
});

export default KulProgressbar;
