'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { type KulPhotoframeCustomEvent, type KulPhotoframeEventPayload } from "ketchup-lite";
import { KulPhotoframe as KulPhotoframeElement, defineCustomElement as defineKulPhotoframe } from "ketchup-lite/dist/components/kul-photoframe.js";
import React from 'react';

type KulPhotoframeEvents = { onKulPhotoframeEvent: EventName<KulPhotoframeCustomEvent<KulPhotoframeEventPayload>> };

const KulPhotoframe: StencilReactComponent<KulPhotoframeElement, KulPhotoframeEvents> = /*@__PURE__*/ createComponent<KulPhotoframeElement, KulPhotoframeEvents>({
    tagName: 'kul-photoframe',
    elementClass: KulPhotoframeElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onKulPhotoframeEvent: 'kul-photoframe-event' } as KulPhotoframeEvents,
    defineCustomElement: defineKulPhotoframe
});

export default KulPhotoframe;
