'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { KulShowcaseTextfield as KulShowcaseTextfieldElement, defineCustomElement as defineKulShowcaseTextfield } from "ketchup-lite/dist/components/kul-showcase-textfield.js";
import React from 'react';

type KulShowcaseTextfieldEvents = NonNullable<unknown>;

const KulShowcaseTextfield: StencilReactComponent<KulShowcaseTextfieldElement, KulShowcaseTextfieldEvents> = /*@__PURE__*/ createComponent<KulShowcaseTextfieldElement, KulShowcaseTextfieldEvents>({
    tagName: 'kul-showcase-textfield',
    elementClass: KulShowcaseTextfieldElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KulShowcaseTextfieldEvents,
    defineCustomElement: defineKulShowcaseTextfield
});

export default KulShowcaseTextfield;
