'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { KulShowcaseToast as KulShowcaseToastElement, defineCustomElement as defineKulShowcaseToast } from "ketchup-lite/dist/components/kul-showcase-toast.js";
import React from 'react';

type KulShowcaseToastEvents = NonNullable<unknown>;

const KulShowcaseToast: StencilReactComponent<KulShowcaseToastElement, KulShowcaseToastEvents> = /*@__PURE__*/ createComponent<KulShowcaseToastElement, KulShowcaseToastEvents>({
    tagName: 'kul-showcase-toast',
    elementClass: KulShowcaseToastElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KulShowcaseToastEvents,
    defineCustomElement: defineKulShowcaseToast
});

export default KulShowcaseToast;
