'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { type KulSplashCustomEvent, type KulSplashEventPayload } from "ketchup-lite";
import { KulSplash as KulSplashElement, defineCustomElement as defineKulSplash } from "ketchup-lite/dist/components/kul-splash.js";
import React from 'react';

type KulSplashEvents = { onKulSplashEvent: EventName<KulSplashCustomEvent<KulSplashEventPayload>> };

const KulSplash: StencilReactComponent<KulSplashElement, KulSplashEvents> = /*@__PURE__*/ createComponent<KulSplashElement, KulSplashEvents>({
    tagName: 'kul-splash',
    elementClass: KulSplashElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onKulSplashEvent: 'kul-splash-event' } as KulSplashEvents,
    defineCustomElement: defineKulSplash
});

export default KulSplash;
