'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { KulShowcaseButton as KulShowcaseButtonElement, defineCustomElement as defineKulShowcaseButton } from "ketchup-lite/dist/components/kul-showcase-button.js";
import React from 'react';

type KulShowcaseButtonEvents = NonNullable<unknown>;

const KulShowcaseButton: StencilReactComponent<KulShowcaseButtonElement, KulShowcaseButtonEvents> = /*@__PURE__*/ createComponent<KulShowcaseButtonElement, KulShowcaseButtonEvents>({
    tagName: 'kul-showcase-button',
    elementClass: KulShowcaseButtonElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KulShowcaseButtonEvents,
    defineCustomElement: defineKulShowcaseButton
});

export default KulShowcaseButton;
