'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { KulShowcaseArticle as KulShowcaseArticleElement, defineCustomElement as defineKulShowcaseArticle } from "ketchup-lite/dist/components/kul-showcase-article.js";
import React from 'react';

type KulShowcaseArticleEvents = NonNullable<unknown>;

const KulShowcaseArticle: StencilReactComponent<KulShowcaseArticleElement, KulShowcaseArticleEvents> = /*@__PURE__*/ createComponent<KulShowcaseArticleElement, KulShowcaseArticleEvents>({
    tagName: 'kul-showcase-article',
    elementClass: KulShowcaseArticleElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KulShowcaseArticleEvents,
    defineCustomElement: defineKulShowcaseArticle
});

export default KulShowcaseArticle;
