'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { KulShowcasePhotoframe as KulShowcasePhotoframeElement, defineCustomElement as defineKulShowcasePhotoframe } from "ketchup-lite/dist/components/kul-showcase-photoframe.js";
import React from 'react';

type KulShowcasePhotoframeEvents = NonNullable<unknown>;

const KulShowcasePhotoframe: StencilReactComponent<KulShowcasePhotoframeElement, KulShowcasePhotoframeEvents> = /*@__PURE__*/ createComponent<KulShowcasePhotoframeElement, KulShowcasePhotoframeEvents>({
    tagName: 'kul-showcase-photoframe',
    elementClass: KulShowcasePhotoframeElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KulShowcasePhotoframeEvents,
    defineCustomElement: defineKulShowcasePhotoframe
});

export default KulShowcasePhotoframe;
