'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { type KulSliderCustomEvent, type KulSliderEventPayload } from "ketchup-lite";
import { KulSlider as KulSliderElement, defineCustomElement as defineKulSlider } from "ketchup-lite/dist/components/kul-slider.js";
import React from 'react';

type KulSliderEvents = { onKulSliderEvent: EventName<KulSliderCustomEvent<KulSliderEventPayload>> };

const KulSlider: StencilReactComponent<KulSliderElement, KulSliderEvents> = /*@__PURE__*/ createComponent<KulSliderElement, KulSliderEvents>({
    tagName: 'kul-slider',
    elementClass: KulSliderElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onKulSliderEvent: 'kul-slider-event' } as KulSliderEvents,
    defineCustomElement: defineKulSlider
});

export default KulSlider;
