'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { KulShowcaseTree as KulShowcaseTreeElement, defineCustomElement as defineKulShowcaseTree } from "ketchup-lite/dist/components/kul-showcase-tree.js";
import React from 'react';

type KulShowcaseTreeEvents = NonNullable<unknown>;

const KulShowcaseTree: StencilReactComponent<KulShowcaseTreeElement, KulShowcaseTreeEvents> = /*@__PURE__*/ createComponent<KulShowcaseTreeElement, KulShowcaseTreeEvents>({
    tagName: 'kul-showcase-tree',
    elementClass: KulShowcaseTreeElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KulShowcaseTreeEvents,
    defineCustomElement: defineKulShowcaseTree
});

export default KulShowcaseTree;
