'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { KulShowcaseProgressbar as KulShowcaseProgressbarElement, defineCustomElement as defineKulShowcaseProgressbar } from "ketchup-lite/dist/components/kul-showcase-progressbar.js";
import React from 'react';

type KulShowcaseProgressbarEvents = NonNullable<unknown>;

const KulShowcaseProgressbar: StencilReactComponent<KulShowcaseProgressbarElement, KulShowcaseProgressbarEvents> = /*@__PURE__*/ createComponent<KulShowcaseProgressbarElement, KulShowcaseProgressbarEvents>({
    tagName: 'kul-showcase-progressbar',
    elementClass: KulShowcaseProgressbarElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KulShowcaseProgressbarEvents,
    defineCustomElement: defineKulShowcaseProgressbar
});

export default KulShowcaseProgressbar;
