'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { KulShowcaseKulllm as KulShowcaseKulllmElement, defineCustomElement as defineKulShowcaseKulllm } from "ketchup-lite/dist/components/kul-showcase-kulllm.js";
import React from 'react';

type KulShowcaseKulllmEvents = NonNullable<unknown>;

const KulShowcaseKulllm: StencilReactComponent<KulShowcaseKulllmElement, KulShowcaseKulllmEvents> = /*@__PURE__*/ createComponent<KulShowcaseKulllmElement, KulShowcaseKulllmEvents>({
    tagName: 'kul-showcase-kulllm',
    elementClass: KulShowcaseKulllmElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KulShowcaseKulllmEvents,
    defineCustomElement: defineKulShowcaseKulllm
});

export default KulShowcaseKulllm;
