'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { KulShowcaseKuldates as KulShowcaseKuldatesElement, defineCustomElement as defineKulShowcaseKuldates } from "ketchup-lite/dist/components/kul-showcase-kuldates.js";
import React from 'react';

type KulShowcaseKuldatesEvents = NonNullable<unknown>;

const KulShowcaseKuldates: StencilReactComponent<KulShowcaseKuldatesElement, KulShowcaseKuldatesEvents> = /*@__PURE__*/ createComponent<KulShowcaseKuldatesElement, KulShowcaseKuldatesEvents>({
    tagName: 'kul-showcase-kuldates',
    elementClass: KulShowcaseKuldatesElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KulShowcaseKuldatesEvents,
    defineCustomElement: defineKulShowcaseKuldates
});

export default KulShowcaseKuldates;
