'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { KulShowcaseImage as KulShowcaseImageElement, defineCustomElement as defineKulShowcaseImage } from "ketchup-lite/dist/components/kul-showcase-image.js";
import React from 'react';

type KulShowcaseImageEvents = NonNullable<unknown>;

const KulShowcaseImage: StencilReactComponent<KulShowcaseImageElement, KulShowcaseImageEvents> = /*@__PURE__*/ createComponent<KulShowcaseImageElement, KulShowcaseImageEvents>({
    tagName: 'kul-showcase-image',
    elementClass: KulShowcaseImageElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KulShowcaseImageEvents,
    defineCustomElement: defineKulShowcaseImage
});

export default KulShowcaseImage;
