'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { KulShowcaseSplash as KulShowcaseSplashElement, defineCustomElement as defineKulShowcaseSplash } from "ketchup-lite/dist/components/kul-showcase-splash.js";
import React from 'react';

type KulShowcaseSplashEvents = NonNullable<unknown>;

const KulShowcaseSplash: StencilReactComponent<KulShowcaseSplashElement, KulShowcaseSplashEvents> = /*@__PURE__*/ createComponent<KulShowcaseSplashElement, KulShowcaseSplashEvents>({
    tagName: 'kul-showcase-splash',
    elementClass: KulShowcaseSplashElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KulShowcaseSplashEvents,
    defineCustomElement: defineKulShowcaseSplash
});

export default KulShowcaseSplash;
