'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { KulShowcaseKultheme as KulShowcaseKulthemeElement, defineCustomElement as defineKulShowcaseKultheme } from "ketchup-lite/dist/components/kul-showcase-kultheme.js";
import React from 'react';

type KulShowcaseKulthemeEvents = NonNullable<unknown>;

const KulShowcaseKultheme: StencilReactComponent<KulShowcaseKulthemeElement, KulShowcaseKulthemeEvents> = /*@__PURE__*/ createComponent<KulShowcaseKulthemeElement, KulShowcaseKulthemeEvents>({
    tagName: 'kul-showcase-kultheme',
    elementClass: KulShowcaseKulthemeElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KulShowcaseKulthemeEvents,
    defineCustomElement: defineKulShowcaseKultheme
});

export default KulShowcaseKultheme;
