'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { KulShowcaseKulscrollonhover as KulShowcaseKulscrollonhoverElement, defineCustomElement as defineKulShowcaseKulscrollonhover } from "ketchup-lite/dist/components/kul-showcase-kulscrollonhover.js";
import React from 'react';

type KulShowcaseKulscrollonhoverEvents = NonNullable<unknown>;

const KulShowcaseKulscrollonhover: StencilReactComponent<KulShowcaseKulscrollonhoverElement, KulShowcaseKulscrollonhoverEvents> = /*@__PURE__*/ createComponent<KulShowcaseKulscrollonhoverElement, KulShowcaseKulscrollonhoverEvents>({
    tagName: 'kul-showcase-kulscrollonhover',
    elementClass: KulShowcaseKulscrollonhoverElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KulShowcaseKulscrollonhoverEvents,
    defineCustomElement: defineKulShowcaseKulscrollonhover
});

export default KulShowcaseKulscrollonhover;
