'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { KulShowcaseChat as KulShowcaseChatElement, defineCustomElement as defineKulShowcaseChat } from "ketchup-lite/dist/components/kul-showcase-chat.js";
import React from 'react';

type KulShowcaseChatEvents = NonNullable<unknown>;

const KulShowcaseChat: StencilReactComponent<KulShowcaseChatElement, KulShowcaseChatEvents> = /*@__PURE__*/ createComponent<KulShowcaseChatElement, KulShowcaseChatEvents>({
    tagName: 'kul-showcase-chat',
    elementClass: KulShowcaseChatElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KulShowcaseChatEvents,
    defineCustomElement: defineKulShowcaseChat
});

export default KulShowcaseChat;
