'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { KulShowcaseKullanguage as KulShowcaseKullanguageElement, defineCustomElement as defineKulShowcaseKullanguage } from "ketchup-lite/dist/components/kul-showcase-kullanguage.js";
import React from 'react';

type KulShowcaseKullanguageEvents = NonNullable<unknown>;

const KulShowcaseKullanguage: StencilReactComponent<KulShowcaseKullanguageElement, KulShowcaseKullanguageEvents> = /*@__PURE__*/ createComponent<KulShowcaseKullanguageElement, KulShowcaseKullanguageEvents>({
    tagName: 'kul-showcase-kullanguage',
    elementClass: KulShowcaseKullanguageElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KulShowcaseKullanguageEvents,
    defineCustomElement: defineKulShowcaseKullanguage
});

export default KulShowcaseKullanguage;
