'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { KulShowcaseImageviewer as KulShowcaseImageviewerElement, defineCustomElement as defineKulShowcaseImageviewer } from "ketchup-lite/dist/components/kul-showcase-imageviewer.js";
import React from 'react';

type KulShowcaseImageviewerEvents = NonNullable<unknown>;

const KulShowcaseImageviewer: StencilReactComponent<KulShowcaseImageviewerElement, KulShowcaseImageviewerEvents> = /*@__PURE__*/ createComponent<KulShowcaseImageviewerElement, KulShowcaseImageviewerEvents>({
    tagName: 'kul-showcase-imageviewer',
    elementClass: KulShowcaseImageviewerElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KulShowcaseImageviewerEvents,
    defineCustomElement: defineKulShowcaseImageviewer
});

export default KulShowcaseImageviewer;
