'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { KulShowcaseDebug as KulShowcaseDebugElement, defineCustomElement as defineKulShowcaseDebug } from "ketchup-lite/dist/components/kul-showcase-debug.js";
import React from 'react';

type KulShowcaseDebugEvents = NonNullable<unknown>;

const KulShowcaseDebug: StencilReactComponent<KulShowcaseDebugElement, KulShowcaseDebugEvents> = /*@__PURE__*/ createComponent<KulShowcaseDebugElement, KulShowcaseDebugEvents>({
    tagName: 'kul-showcase-debug',
    elementClass: KulShowcaseDebugElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KulShowcaseDebugEvents,
    defineCustomElement: defineKulShowcaseDebug
});

export default KulShowcaseDebug;
