'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { KulShowcaseKuldata as KulShowcaseKuldataElement, defineCustomElement as defineKulShowcaseKuldata } from "ketchup-lite/dist/components/kul-showcase-kuldata.js";
import React from 'react';

type KulShowcaseKuldataEvents = NonNullable<unknown>;

const KulShowcaseKuldata: StencilReactComponent<KulShowcaseKuldataElement, KulShowcaseKuldataEvents> = /*@__PURE__*/ createComponent<KulShowcaseKuldataElement, KulShowcaseKuldataEvents>({
    tagName: 'kul-showcase-kuldata',
    elementClass: KulShowcaseKuldataElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KulShowcaseKuldataEvents,
    defineCustomElement: defineKulShowcaseKuldata
});

export default KulShowcaseKuldata;
