'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { KulShowcaseList as KulShowcaseListElement, defineCustomElement as defineKulShowcaseList } from "ketchup-lite/dist/components/kul-showcase-list.js";
import React from 'react';

type KulShowcaseListEvents = NonNullable<unknown>;

const KulShowcaseList: StencilReactComponent<KulShowcaseListElement, KulShowcaseListEvents> = /*@__PURE__*/ createComponent<KulShowcaseListElement, KulShowcaseListEvents>({
    tagName: 'kul-showcase-list',
    elementClass: KulShowcaseListElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KulShowcaseListEvents,
    defineCustomElement: defineKulShowcaseList
});

export default KulShowcaseList;
