'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { KulShowcaseChip as KulShowcaseChipElement, defineCustomElement as defineKulShowcaseChip } from "ketchup-lite/dist/components/kul-showcase-chip.js";
import React from 'react';

type KulShowcaseChipEvents = NonNullable<unknown>;

const KulShowcaseChip: StencilReactComponent<KulShowcaseChipElement, KulShowcaseChipEvents> = /*@__PURE__*/ createComponent<KulShowcaseChipElement, KulShowcaseChipEvents>({
    tagName: 'kul-showcase-chip',
    elementClass: KulShowcaseChipElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KulShowcaseChipEvents,
    defineCustomElement: defineKulShowcaseChip
});

export default KulShowcaseChip;
