'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { KulShowcaseMasonry as KulShowcaseMasonryElement, defineCustomElement as defineKulShowcaseMasonry } from "ketchup-lite/dist/components/kul-showcase-masonry.js";
import React from 'react';

type KulShowcaseMasonryEvents = NonNullable<unknown>;

const KulShowcaseMasonry: StencilReactComponent<KulShowcaseMasonryElement, KulShowcaseMasonryEvents> = /*@__PURE__*/ createComponent<KulShowcaseMasonryElement, KulShowcaseMasonryEvents>({
    tagName: 'kul-showcase-masonry',
    elementClass: KulShowcaseMasonryElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KulShowcaseMasonryEvents,
    defineCustomElement: defineKulShowcaseMasonry
});

export default KulShowcaseMasonry;
