'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { KulShowcaseBadge as KulShowcaseBadgeElement, defineCustomElement as defineKulShowcaseBadge } from "ketchup-lite/dist/components/kul-showcase-badge.js";
import React from 'react';

type KulShowcaseBadgeEvents = NonNullable<unknown>;

const KulShowcaseBadge: StencilReactComponent<KulShowcaseBadgeElement, KulShowcaseBadgeEvents> = /*@__PURE__*/ createComponent<KulShowcaseBadgeElement, KulShowcaseBadgeEvents>({
    tagName: 'kul-showcase-badge',
    elementClass: KulShowcaseBadgeElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KulShowcaseBadgeEvents,
    defineCustomElement: defineKulShowcaseBadge
});

export default KulShowcaseBadge;
