'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { KulShowcaseMessenger as KulShowcaseMessengerElement, defineCustomElement as defineKulShowcaseMessenger } from "ketchup-lite/dist/components/kul-showcase-messenger.js";
import React from 'react';

type KulShowcaseMessengerEvents = NonNullable<unknown>;

const KulShowcaseMessenger: StencilReactComponent<KulShowcaseMessengerElement, KulShowcaseMessengerEvents> = /*@__PURE__*/ createComponent<KulShowcaseMessengerElement, KulShowcaseMessengerEvents>({
    tagName: 'kul-showcase-messenger',
    elementClass: KulShowcaseMessengerElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KulShowcaseMessengerEvents,
    defineCustomElement: defineKulShowcaseMessenger
});

export default KulShowcaseMessenger;
