'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { KulShowcaseCard as KulShowcaseCardElement, defineCustomElement as defineKulShowcaseCard } from "ketchup-lite/dist/components/kul-showcase-card.js";
import React from 'react';

type KulShowcaseCardEvents = NonNullable<unknown>;

const KulShowcaseCard: StencilReactComponent<KulShowcaseCardElement, KulShowcaseCardEvents> = /*@__PURE__*/ createComponent<KulShowcaseCardElement, KulShowcaseCardEvents>({
    tagName: 'kul-showcase-card',
    elementClass: KulShowcaseCardElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KulShowcaseCardEvents,
    defineCustomElement: defineKulShowcaseCard
});

export default KulShowcaseCard;
