'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { KulShowcaseSpinner as KulShowcaseSpinnerElement, defineCustomElement as defineKulShowcaseSpinner } from "ketchup-lite/dist/components/kul-showcase-spinner.js";
import React from 'react';

type KulShowcaseSpinnerEvents = NonNullable<unknown>;

const KulShowcaseSpinner: StencilReactComponent<KulShowcaseSpinnerElement, KulShowcaseSpinnerEvents> = /*@__PURE__*/ createComponent<KulShowcaseSpinnerElement, KulShowcaseSpinnerEvents>({
    tagName: 'kul-showcase-spinner',
    elementClass: KulShowcaseSpinnerElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KulShowcaseSpinnerEvents,
    defineCustomElement: defineKulShowcaseSpinner
});

export default KulShowcaseSpinner;
