'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { KulShowcaseKuldynamicposition as KulShowcaseKuldynamicpositionElement, defineCustomElement as defineKulShowcaseKuldynamicposition } from "ketchup-lite/dist/components/kul-showcase-kuldynamicposition.js";
import React from 'react';

type KulShowcaseKuldynamicpositionEvents = NonNullable<unknown>;

const KulShowcaseKuldynamicposition: StencilReactComponent<KulShowcaseKuldynamicpositionElement, KulShowcaseKuldynamicpositionEvents> = /*@__PURE__*/ createComponent<KulShowcaseKuldynamicpositionElement, KulShowcaseKuldynamicpositionEvents>({
    tagName: 'kul-showcase-kuldynamicposition',
    elementClass: KulShowcaseKuldynamicpositionElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KulShowcaseKuldynamicpositionEvents,
    defineCustomElement: defineKulShowcaseKuldynamicposition
});

export default KulShowcaseKuldynamicposition;
