'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { KulShowcase as KulShowcaseElement, defineCustomElement as defineKulShowcase } from "ketchup-lite/dist/components/kul-showcase.js";
import React from 'react';

type KulShowcaseEvents = NonNullable<unknown>;

const KulShowcase: StencilReactComponent<KulShowcaseElement, KulShowcaseEvents> = /*@__PURE__*/ createComponent<KulShowcaseElement, KulShowcaseEvents>({
    tagName: 'kul-showcase',
    elementClass: KulShowcaseElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KulShowcaseEvents,
    defineCustomElement: defineKulShowcase
});

export default KulShowcase;
