'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { KulShowcaseToggle as KulShowcaseToggleElement, defineCustomElement as defineKulShowcaseToggle } from "ketchup-lite/dist/components/kul-showcase-toggle.js";
import React from 'react';

type KulShowcaseToggleEvents = NonNullable<unknown>;

const KulShowcaseToggle: StencilReactComponent<KulShowcaseToggleElement, KulShowcaseToggleEvents> = /*@__PURE__*/ createComponent<KulShowcaseToggleElement, KulShowcaseToggleEvents>({
    tagName: 'kul-showcase-toggle',
    elementClass: KulShowcaseToggleElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KulShowcaseToggleEvents,
    defineCustomElement: defineKulShowcaseToggle
});

export default KulShowcaseToggle;
