'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { KulShowcaseKulmanager as KulShowcaseKulmanagerElement, defineCustomElement as defineKulShowcaseKulmanager } from "ketchup-lite/dist/components/kul-showcase-kulmanager.js";
import React from 'react';

type KulShowcaseKulmanagerEvents = NonNullable<unknown>;

const KulShowcaseKulmanager: StencilReactComponent<KulShowcaseKulmanagerElement, KulShowcaseKulmanagerEvents> = /*@__PURE__*/ createComponent<KulShowcaseKulmanagerElement, KulShowcaseKulmanagerEvents>({
    tagName: 'kul-showcase-kulmanager',
    elementClass: KulShowcaseKulmanagerElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KulShowcaseKulmanagerEvents,
    defineCustomElement: defineKulShowcaseKulmanager
});

export default KulShowcaseKulmanager;
