'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { KulShowcaseCarousel as KulShowcaseCarouselElement, defineCustomElement as defineKulShowcaseCarousel } from "ketchup-lite/dist/components/kul-showcase-carousel.js";
import React from 'react';

type KulShowcaseCarouselEvents = NonNullable<unknown>;

const KulShowcaseCarousel: StencilReactComponent<KulShowcaseCarouselElement, KulShowcaseCarouselEvents> = /*@__PURE__*/ createComponent<KulShowcaseCarouselElement, KulShowcaseCarouselEvents>({
    tagName: 'kul-showcase-carousel',
    elementClass: KulShowcaseCarouselElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KulShowcaseCarouselEvents,
    defineCustomElement: defineKulShowcaseCarousel
});

export default KulShowcaseCarousel;
