'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { KulShowcaseChart as KulShowcaseChartElement, defineCustomElement as defineKulShowcaseChart } from "ketchup-lite/dist/components/kul-showcase-chart.js";
import React from 'react';

type KulShowcaseChartEvents = NonNullable<unknown>;

const KulShowcaseChart: StencilReactComponent<KulShowcaseChartElement, KulShowcaseChartEvents> = /*@__PURE__*/ createComponent<KulShowcaseChartElement, KulShowcaseChartEvents>({
    tagName: 'kul-showcase-chart',
    elementClass: KulShowcaseChartElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KulShowcaseChartEvents,
    defineCustomElement: defineKulShowcaseChart
});

export default KulShowcaseChart;
