'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { KulShowcaseSlider as KulShowcaseSliderElement, defineCustomElement as defineKulShowcaseSlider } from "ketchup-lite/dist/components/kul-showcase-slider.js";
import React from 'react';

type KulShowcaseSliderEvents = NonNullable<unknown>;

const KulShowcaseSlider: StencilReactComponent<KulShowcaseSliderElement, KulShowcaseSliderEvents> = /*@__PURE__*/ createComponent<KulShowcaseSliderElement, KulShowcaseSliderEvents>({
    tagName: 'kul-showcase-slider',
    elementClass: KulShowcaseSliderElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KulShowcaseSliderEvents,
    defineCustomElement: defineKulShowcaseSlider
});

export default KulShowcaseSlider;
