'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { KulShowcaseDrawer as KulShowcaseDrawerElement, defineCustomElement as defineKulShowcaseDrawer } from "ketchup-lite/dist/components/kul-showcase-drawer.js";
import React from 'react';

type KulShowcaseDrawerEvents = NonNullable<unknown>;

const KulShowcaseDrawer: StencilReactComponent<KulShowcaseDrawerElement, KulShowcaseDrawerEvents> = /*@__PURE__*/ createComponent<KulShowcaseDrawerElement, KulShowcaseDrawerEvents>({
    tagName: 'kul-showcase-drawer',
    elementClass: KulShowcaseDrawerElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KulShowcaseDrawerEvents,
    defineCustomElement: defineKulShowcaseDrawer
});

export default KulShowcaseDrawer;
