'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { KulShowcaseHeader as KulShowcaseHeaderElement, defineCustomElement as defineKulShowcaseHeader } from "ketchup-lite/dist/components/kul-showcase-header.js";
import React from 'react';

type KulShowcaseHeaderEvents = NonNullable<unknown>;

const KulShowcaseHeader: StencilReactComponent<KulShowcaseHeaderElement, KulShowcaseHeaderEvents> = /*@__PURE__*/ createComponent<KulShowcaseHeaderElement, KulShowcaseHeaderEvents>({
    tagName: 'kul-showcase-header',
    elementClass: KulShowcaseHeaderElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KulShowcaseHeaderEvents,
    defineCustomElement: defineKulShowcaseHeader
});

export default KulShowcaseHeader;
