'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { KulShowcaseLazy as KulShowcaseLazyElement, defineCustomElement as defineKulShowcaseLazy } from "ketchup-lite/dist/components/kul-showcase-lazy.js";
import React from 'react';

type KulShowcaseLazyEvents = NonNullable<unknown>;

const KulShowcaseLazy: StencilReactComponent<KulShowcaseLazyElement, KulShowcaseLazyEvents> = /*@__PURE__*/ createComponent<KulShowcaseLazyElement, KulShowcaseLazyEvents>({
    tagName: 'kul-showcase-lazy',
    elementClass: KulShowcaseLazyElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KulShowcaseLazyEvents,
    defineCustomElement: defineKulShowcaseLazy
});

export default KulShowcaseLazy;
