'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { KulShowcaseCompare as KulShowcaseCompareElement, defineCustomElement as defineKulShowcaseCompare } from "ketchup-lite/dist/components/kul-showcase-compare.js";
import React from 'react';

type KulShowcaseCompareEvents = NonNullable<unknown>;

const KulShowcaseCompare: StencilReactComponent<KulShowcaseCompareElement, KulShowcaseCompareEvents> = /*@__PURE__*/ createComponent<KulShowcaseCompareElement, KulShowcaseCompareEvents>({
    tagName: 'kul-showcase-compare',
    elementClass: KulShowcaseCompareElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KulShowcaseCompareEvents,
    defineCustomElement: defineKulShowcaseCompare
});

export default KulShowcaseCompare;
