'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { type KulToastCustomEvent, type KulToastEventPayload } from "ketchup-lite";
import { KulToast as KulToastElement, defineCustomElement as defineKulToast } from "ketchup-lite/dist/components/kul-toast.js";
import React from 'react';

type KulToastEvents = { onKulToastEvent: EventName<KulToastCustomEvent<KulToastEventPayload>> };

const KulToast: StencilReactComponent<KulToastElement, KulToastEvents> = /*@__PURE__*/ createComponent<KulToastElement, KulToastEvents>({
    tagName: 'kul-toast',
    elementClass: KulToastElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onKulToastEvent: 'kul-toast-event' } as KulToastEvents,
    defineCustomElement: defineKulToast
});

export default KulToast;
