'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { type KulTabbarCustomEvent, type KulTabbarEventPayload } from "ketchup-lite";
import { KulTabbar as KulTabbarElement, defineCustomElement as defineKulTabbar } from "ketchup-lite/dist/components/kul-tabbar.js";
import React from 'react';

type KulTabbarEvents = { onKulTabbarEvent: EventName<KulTabbarCustomEvent<KulTabbarEventPayload>> };

const KulTabbar: StencilReactComponent<KulTabbarElement, KulTabbarEvents> = /*@__PURE__*/ createComponent<KulTabbarElement, KulTabbarEvents>({
    tagName: 'kul-tabbar',
    elementClass: KulTabbarElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onKulTabbarEvent: 'kul-tabbar-event' } as KulTabbarEvents,
    defineCustomElement: defineKulTabbar
});

export default KulTabbar;
