'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { type KulTypewriterCustomEvent, type KulTypewriterEventPayload } from "ketchup-lite";
import { KulTypewriter as KulTypewriterElement, defineCustomElement as defineKulTypewriter } from "ketchup-lite/dist/components/kul-typewriter.js";
import React from 'react';

type KulTypewriterEvents = { onKulTypewriterEvent: EventName<KulTypewriterCustomEvent<KulTypewriterEventPayload>> };

const KulTypewriter: StencilReactComponent<KulTypewriterElement, KulTypewriterEvents> = /*@__PURE__*/ createComponent<KulTypewriterElement, KulTypewriterEvents>({
    tagName: 'kul-typewriter',
    elementClass: KulTypewriterElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onKulTypewriterEvent: 'kul-typewriter-event' } as KulTypewriterEvents,
    defineCustomElement: defineKulTypewriter
});

export default KulTypewriter;
