'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { type KulToggleCustomEvent, type KulToggleEventPayload } from "ketchup-lite";
import { KulToggle as KulToggleElement, defineCustomElement as defineKulToggle } from "ketchup-lite/dist/components/kul-toggle.js";
import React from 'react';

type KulToggleEvents = { onKulToggleEvent: EventName<KulToggleCustomEvent<KulToggleEventPayload>> };

const KulToggle: StencilReactComponent<KulToggleElement, KulToggleEvents> = /*@__PURE__*/ createComponent<KulToggleElement, KulToggleEvents>({
    tagName: 'kul-toggle',
    elementClass: KulToggleElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onKulToggleEvent: 'kul-toggle-event' } as KulToggleEvents,
    defineCustomElement: defineKulToggle
});

export default KulToggle;
