'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { type KulTreeCustomEvent, type KulTreeEventPayload } from "ketchup-lite";
import { KulTree as KulTreeElement, defineCustomElement as defineKulTree } from "ketchup-lite/dist/components/kul-tree.js";
import React from 'react';

type KulTreeEvents = { onKulTreeEvent: EventName<KulTreeCustomEvent<KulTreeEventPayload>> };

const KulTree: StencilReactComponent<KulTreeElement, KulTreeEvents> = /*@__PURE__*/ createComponent<KulTreeElement, KulTreeEvents>({
    tagName: 'kul-tree',
    elementClass: KulTreeElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onKulTreeEvent: 'kul-tree-event' } as KulTreeEvents,
    defineCustomElement: defineKulTree
});

export default KulTree;
