'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { type KulUploadCustomEvent, type KulUploadEventPayload } from "ketchup-lite";
import { KulUpload as KulUploadElement, defineCustomElement as defineKulUpload } from "ketchup-lite/dist/components/kul-upload.js";
import React from 'react';

type KulUploadEvents = { onKulUploadEvent: EventName<KulUploadCustomEvent<KulUploadEventPayload>> };

const KulUpload: StencilReactComponent<KulUploadElement, KulUploadEvents> = /*@__PURE__*/ createComponent<KulUploadElement, KulUploadEvents>({
    tagName: 'kul-upload',
    elementClass: KulUploadElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onKulUploadEvent: 'kul-upload-event' } as KulUploadEvents,
    defineCustomElement: defineKulUpload
});

export default KulUpload;
