name: Version bump (candidate)

on:
  push:
    branches:
      - candidate

jobs:
  version-bump:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # Set to false to prevent using the token in the checkout, as the action will handle authentication
          persist-credentials: false

      - name: Setup and Build
        uses: ./.github/actions/setup
        with:
          node-version: '18.x'
          install-immutable: 'true'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Bump Versions with Lerna (Prerelease)
        run: |
          npx lerna version prerelease --preid=rc --no-push --yes

      - name: Build Packages
        run: yarn build

      - name: Format Code with Prettier
        run: yarn format

      - name: Check for Changes
        run: |
          if git diff --quiet && git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

      - name: Create or Update Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'chore: bump versions for release candidate [skip ci]'
          branch: 'version-bump-rc'
          title: 'chore: bump versions for release candidate'
          body: 'This PR bumps package versions for the release candidate.'
          base: 'candidate'
          labels: 'automated PR'
