name: Publish NPM Package on merge (candidate)

on:
    push:
        branches:
            - candidate

jobs:
    candidate-package:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Clear Yarn cache
              run: yarn cache clean

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '18.x'
                  registry-url: 'https://registry.npmjs.org'

            - name: Install dependencies
              run: yarn install --no-immutable

            - name: Update Version for Ketchup Lite
              run: |
                  VERSION=$(node -p "require('./packages/ketchup-lite/package.json').version")
                  TIMESTAMP=$(date +%Y%m%d%H%M%S)
                  NEW_VERSION="${VERSION}-${TIMESTAMP}"
                  echo "New version: $NEW_VERSION"
                  jq ".version = \"$NEW_VERSION\"" packages/ketchup-lite/package.json > temp.json && mv temp.json packages/ketchup-lite/package.json

            - name: Update Version for Ketchup Lite React
              run: |
                  VERSION=$(node -p "require('./packages/ketchup-lite-react/package.json').version")
                  TIMESTAMP=$(date +%Y%m%d%H%M%S)
                  NEW_VERSION="${VERSION}-${TIMESTAMP}"
                  echo "New version: $NEW_VERSION"
                  jq ".version = \"$NEW_VERSION\"" packages/ketchup-lite-react/package.json > temp.json && mv temp.json packages/ketchup-lite-react/package.json

            - name: Update Version for Ketchup Lite React (SSR)
              run: |
                  VERSION=$(node -p "require('./packages/ketchup-lite-react-ssr/package.json').version")
                  TIMESTAMP=$(date +%Y%m%d%H%M%S)
                  NEW_VERSION="${VERSION}-${TIMESTAMP}"
                  echo "New version: $NEW_VERSION"
                  jq ".version = \"$NEW_VERSION\"" packages/ketchup-lite-react-ssr/package.json > temp.json && mv temp.json packages/ketchup-lite-react-ssr/package.json

            - name: Update Version for Ketchup Lite (Hydrate for SSR)
              run: |
                  VERSION=$(node -p "require('./packages/ketchup-lite-hydrate/package.json').version")
                  TIMESTAMP=$(date +%Y%m%d%H%M%S)
                  NEW_VERSION="${VERSION}-${TIMESTAMP}"
                  echo "New version: $NEW_VERSION"
                  jq ".version = \"$NEW_VERSION\"" packages/ketchup-lite-hydrate/package.json > temp.json && mv temp.json packages/ketchup-lite-hydrate/package.json

            - name: Build Packages
              run: |
                  yarn build
