name: Components count

on:
    push:
        branches:
            - main

jobs:
    count-components:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Count Components
              run: |
                  COUNT=$(ls -l packages/ketchup-lite/src/components | grep '^d' | wc -l)
                  echo "{ \"components\": $COUNT }" > count.json

            - name: Configure Git
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

            - name: Commit and Push Changes
              run: |
                  git add count.json
                  git commit -m "Updated component count"
                  git push origin main
