name: Publish NPM Package on merge (main)

on:
    push:
        branches:
            - main

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Count Components
              run: |
                  COUNT=$(ls -l packages/ketchup-lite/src/components | grep '^d' | wc -l)
                  echo "{ \"components\": $COUNT }" > count.json

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v5
              with:
                  commit-message: 'Updated component count'
                  branch: 'update-component-count-${{ github.run_id }}'
                  title: 'Update component count'
                  body: 'Automatically updates the component count.'
                  labels: 'automated PR'

            - name: Clear Yarn cache
              run: yarn cache clean

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '18.x'
                  registry-url: 'https://registry.npmjs.org'

            - name: Install dependencies
              run: yarn install --immutable

            - name: Build Ketchup Lite
              run: yarn build

            - name: Publish Ketchup Lite
              if: github.ref == 'refs/heads/main'
              run: |
                  cd packages/ketchup-lite
                  yarn publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish Ketchup Lite React
              if: github.ref == 'refs/heads/main'
              run: |
                  cd packages/ketchup-lite-react
                  yarn publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
