name: Publish NPM Package (Candidate)

on:
    push:
        branches:
            - candidate

jobs:
    publish-candidate:
        uses: ./.github/workflows/setup.yml
        with:
            node-version: '18.x'
            install-immutable: false
        secrets:
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    version-and-publish:
        needs: publish-candidate
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Update Versions for All Packages
              run: |
                  PACKAGES=("ketchup-lite" "ketchup-lite-react" "ketchup-lite-react-ssr" "ketchup-lite-hydrate")
                  TIMESTAMP=$(date +%Y%m%d%H%M%S)
                  for pkg in "${PACKAGES[@]}"; do
                    VERSION=$(node -p "require('./packages/${pkg}/package.json').version")
                    NEW_VERSION="${VERSION}-${TIMESTAMP}"
                    echo "Updating ${pkg} version to ${NEW_VERSION}"
                    jq ".version = \"${NEW_VERSION}\"" packages/${pkg}/package.json > temp.json && mv temp.json packages/${pkg}/package.json
                  done

            - name: Commit Version Bumps
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"
                  git add packages/*/package.json
                  git commit -m "Bump versions for candidate release [skip ci]"
                  git push origin candidate

            - name: Publish Packages to NPM
              run: |
                  PACKAGES=("ketchup-lite" "ketchup-lite-react" "ketchup-lite-react-ssr" "ketchup-lite-hydrate")
                  for pkg in "${PACKAGES[@]}"; do
                    cd packages/${pkg}
                    npm publish --tag rc
                    cd ../../
                  done
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
