name: Publish NPM Package (Main)

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      bump:
        description: 'Type of version bump'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for Lerna to access the full history

      - name: Setup and Build
        uses: ./.github/actions/setup
        with:
          node-version: '18.x'
          install-immutable: 'true'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump Versions with Lerna (Release)
        run: |
          npx lerna version ${{ github.event.inputs.bump }} --no-push --yes --allow-dirty
        if: ${{ github.event_name == 'workflow_dispatch' }}

      - name: Bump Versions with Lerna (Release) - Conventional Commits
        run: |
          npx lerna version --conventional-commits --no-push --yes
        if: ${{ github.event_name == 'push' }}

      - name: Publish Packages with Lerna
        run: |
          npx lerna publish from-package --yes --npm-tag=latest
